image: node:lts-slim

clone:
 depth: full

test: &test
  step:
    name: Test
    caches:
      - node
    script:
      - npm install
      - npm test

lint: &lint
  step:
    name: Lint
    caches:
      - node
    script:
      - npm install
      - npm run lint

pipelines:
  default:
    - <<: *lint
    - <<: *test

  branches:
    master:
      - <<: *lint
      - <<: *test
      - step:
          name: Deploy to production
          deployment: production
          image: alpine/git:latest
          script:
            - git push https://heroku:${HEROKU_API_KEY}@git.heroku.com/${HEROKU_APP_NAME}.git HEAD
